version: '3.8'

services:
  customer-db:
    image: postgres:15
    container_name: customer-db
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    networks:
      - banking-network
    volumes:
      - customer-data:/var/lib/postgresql/data

  transaction-db:
    image: postgres:15
    container_name: transaction-db
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    networks:
      - banking-network
    volumes:
      - transaction-data:/var/lib/postgresql/data

  ms-core:
    build:
      context: ./ms-core
    container_name: ms-core
    ports:
      - "8080:8080"
    depends_on:
      - ms-customer
      - ms-transaction
    networks:
      - banking-network
    environment:
      CLIENT_MS_CUSTOMER_URL: http://ms-customer:8080
      CLIENT_MS_TRANSACTION_URL: http://ms-transaction:8080
      SECURITY_SECRET_KEY: ${SECURITY_SECRET_KEY:-fb04617512your-secret-key-here-make-it-64-chars-long-for-security}

  ms-customer:
    build:
      context: ./ms-customer
    container_name: ms-customer
    ports:
      - "8081:8080"
    depends_on:
      - customer-db
    networks:
      - banking-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/customerdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SECURITY_SECRET_KEY: ${SECURITY_SECRET_KEY:-fb04617512your-secret-key-here-make-it-64-chars-long-for-security}

  ms-transaction:
    build:
      context: ./ms-transaction
    container_name: ms-transaction
    ports:
      - "8082:8080"
    depends_on:
      - transaction-db
    networks:
      - banking-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transaction-db:5432/transactiondb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SECURITY_SECRET_KEY: ${SECURITY_SECRET_KEY:-fb04617512your-secret-key-here-make-it-64-chars-long-for-security}

networks:
  banking-network:

volumes:
  customer-data:
  transaction-data: