client:
  ms-customer:
    url: http://ms-customer:8080
#    url: http://localhost:8083
  ms-transaction:
    url: http://ms-transaction:8080
#    url: http://localhost:8084


security:
  secret-key: fb04617512345678901234567890123456789012345678901234567890123456
  expiration: 3600000

feign:
  client:
    config:
      default:
        requestInterceptors:
          - com.example.config.FeignConfig